apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
     app: nginx-svc
spec:
  ports: 
  - name: http-80
    port: 8887
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-pod
