#生存检测
#检测主容器里的进程
apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
  namespace: default
spec:
  containers:
  - name: liveness-c
    image: httpd:v1
    livenessProbe:
      exec: 
        command: ['test','-f','/var/www/html/index.html']
      initialDelaySeconds: 1
      #第一次检测完后，每三秒检测一次
      periodSeconds: 3
