apiVersion: v1
kind: Pod
metadata:
  name: env2-spec
  namespace: test
spec:
  restartPolicy: Never
  containers:
    - name: test-container
      image: busybox
      command: ["/bin/sh","-c","env"]
      envFrom:
        - configMapRef:
            name: spec-config
