apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
  labels:
     app: httpd-svc
spec:
  type: NodePort
  ports: 
  - name: http-80
    port: 8887
    protocol: TCP
    targetPort: 80
  selector:
    app: httpd-pod
