apiVersion: v1
kind: Service
metadata:
  name: httpd-svc-v2
  labels:
    app: httpd-svc-v2
spec:
  ports: 
  - name: http-80
    port: 8882
    protocol: TCP
    targetPort: 80
  selector:
    app: httpd-pod-v2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-v2
  labels:
    app: httpd-deployment-v2
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: httpd-pod-v2
  template:
    metadata:
      labels:
        app: httpd-pod-v2
    spec:
      containers:
      - name: httpd-container-v2
        image: httpd:v2
        ports:
        - containerPort: 80

