apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test1
spec:
  rules:
    - host: www.test1.com
      http:
        paths:
        - path: /
          backend:
            serviceName: httpd-svc-v1
            servicePort: 8881
