#计算资源配额
apiVersion: v1
kind: ResourceQuota
metadata: 
  name: test_ns_quota
  namespace: test
spec:
  hard: 
    pods: "3"
    requests.cpu: "3"
    request.memory: 100Gi
    limits.cpu: "40"
    limits.memory: 200Gi
