apiVersion: v1
kind: Service
metadata:
  name: httpd-headless-svc1
  labels:
     app: httpd-svc
spec:
  ports: 
  - name: http-80
    port: 8887
    protocol: TCP
    targetPort: 80
  selector:
    app: httpd-pod
  clusterIP: "None"

