apiVersion: v1
kind: Pod
metadata:
  labels:
    name: pod1
  name: pod1
spec:
  volumes:
  - name: secrets
    secret:
      secretName: secret1
  containers:
  - image: httpd:v1
    name: db
    volumeMounts:
    - name: secrets
      mountPath: "/etc/secrets"
      readOnly: true
